DISCOVERY = "discovery"
INVESTIGATION_PLANNER = "investigation_planner"
SKILL_DISPATCHER = "skill_dispatcher"
SKILL_EXECUTOR = "skill_executor"
EVIDENCE_COLLECTOR = "evidence_collector"
EVIDENCE_CORRELATOR = "evidence_correlator"
FINDING_REVIEWER = "finding_reviewer"
REPORT_BUILDER = "report_builder"
