DISCOVERY = "discovery"
ORCHESTRATOR = "orchestrator"
EXECUTION_PLANNER = "execution_planner"
EXECUTE_PLAN = "execute_plan"
STAGE_ADVANCE = "stage_advance"
CROSS_ANALYZER = "cross_analyzer"
REPORT_REVIEWER = "report_reviewer"
