### Ingest — start a batch fetch job
# @name ingest
POST {{workers_url}}/ingest
Content-Type: application/json

{
  "entity_types": ["npm", "github_issues", "github_releases", "github_advisories"],
  "items": ["express", "lodash", "react"]
}


### Ingest — npm only
POST {{workers_url}}/ingest
Content-Type: application/json

{
  "entity_types": ["npm"],
  "items": ["express", "lodash"]
}


### Get job status
GET {{workers_url}}/status/{{ingest.job_ids.npm}}
